name: Report a bug
description: File a bug report.
title: "bug: "
labels: ["bug", "triage"]
type: bug
assignees:
- edera-dev/engineering
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  id: version
  attributes:
    label: Version / Commit
    description: What version of Sprout are you running?
  validations:
    required: true
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Log output
    description: Please provide any relevant log output.
    render: log
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this report, you agree to follow our [Code of Conduct](https://github.com/edera-dev/sprout/blob/main/CODE_OF_CONDUCT.md).
    options:
    - label: I agree to follow the Sprout Code of Conduct.
      required: true
