blank_issues_enabled: true
contact_links:
- name: Ask a question
  url: https://github.com/edera-dev/sprout/discussions
  about: Please ask and answer questions here.
# Note that GitHub will automatically display our security policy in the new issue form.
