blank_issues_enabled: true
contact_links:
- name: Community Discussions
  url: https://github.com/edera-dev/sprout/discussions
  about: Please ask and answer questions here.
- name: Security Advisory
  url: https://github.com/edera-dev/sprout/security/advisories/new
  about: Please report security vulnerabilities here.
