version = 1

[extractors.boot.filesystem-device-match]
has-item = "\\EFI\\BOOT\\shell.efi"

[actions.chainload-shell]
chainload.path = "$boot\\EFI\\BOOT\\shell.efi"

[entries.xen]
title = "Boot Shell"
actions = ["chainload-shell"]
