version = 1

[options]
default-entry = "shell"
menu-timeout = 0

[extractors.boot.filesystem-device-match]
has-item = "\\EFI\\BOOT\\shell.efi"

[actions.chainload-shell]
chainload.path = "$boot\\EFI\\BOOT\\shell.efi"

[entries.shell]
title = "Boot Shell"
actions = ["chainload-shell"]
