version = 1

[values]
default-options = "tty=hvc0"

[actions.welcome]
print.text = "Welcome to Sprout!"

[actions.splash]
splash.image = "edera-splash.png"
splash.time = 5

[actions.chainload-kernel]
chainload.path = "$path"
chainload.options = ["$default-options"]

[generators.kernels.matrix]
entry.title = "Boot Kernel $name"
entry.values.path = "\\EFI\\BOOT\\$name"
entry.actions = ["chainload-kernel"]
values.name = ["kernel.efi"]

[[phases.startup]]
actions = ["splash", "welcome"]
